### ISSUE TITLE
CI: Miri flag passing needs to be fixed

### ISSUE THREAD

**Issue by RalfJung** [Kixiron/crunch-lang#48]
With https://github.com/rust-lang/miri/pull/1769 having landed, this way of passing Miri flags will soon stop working:
https://github.com/Kixiron/crunch-lang/blob/e51945a8c3ecddb49c072de83b372373de0d4b39/.github/workflows/main.yml#L255

This should now instead be
```
MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri test
```

**Comment by Kixiron** [comment]
Fixed in b4ef3fc256f30b97cc5abf3eed491111337b3db0, thanks!
